name: asl
description: "Asl, store and view your family tree in the best way."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0-60.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  graphview:
    path: graphview/

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.4
  dartz: ^0.10.1
  injectable: ^2.4.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  uuid: ^4.4.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  flutter_bloc: ^8.1.5
  auto_route: ^8.1.3
  get_it: ^7.7.0
  firebase_core: ^3.1.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  equatable: ^2.0.5
  collection: ^1.18.0

dependency_overrides:
  intl: ^0.20.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^6.7.0
  flutter_lints: ^3.0.2
  injectable_generator: ^2.6.1
  auto_route_generator: ^8.0.0
  build_runner: null
  freezed: ^2.5.3
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true

  fonts:
    - family: ghaithsans
      fonts:
        - asset: assets/fonts/ghaithsans/ghaithsans_regular.otf
          weight: 400
        - asset: assets/fonts/ghaithsans/ghaithsans_medium.otf
          weight: 500
        - asset: assets/fonts/ghaithsans/ghaithsans_semibold.otf
          weight: 600
        - asset: assets/fonts/ghaithsans/ghaithsans_bold.otf
          weight: 700
        - asset: assets/fonts/ghaithsans/ghaithsans_extrabold.otf
          weight: 800
        - asset: assets/fonts/ghaithsans/ghaithsans_black.otf
          weight: 900
        - asset: assets/fonts/ghaithsans/ghaithsans_light.otf
          weight: 300
        - asset: assets/fonts/ghaithsans/ghaithsans_extralight.otf
          weight: 200
        - asset: assets/fonts/ghaithsans/ghaithsans_thin.otf
          weight: 100

    - family: the_year_of_handicrafts
      fonts:
        - asset: assets/fonts/the_year_of_handicrafts/the_year_of_handicrafts_regular.otf
          weight: 400
        - asset: assets/fonts/the_year_of_handicrafts/the_year_of_handicrafts_medium.otf
          weight: 500
        - asset: assets/fonts/the_year_of_handicrafts/the_year_of_handicrafts_semibold.otf
          weight: 600
        - asset: assets/fonts/the_year_of_handicrafts/the_year_of_handicrafts_bold.otf
          weight: 700
        - asset: assets/fonts/the_year_of_handicrafts/the_year_of_handicrafts_black.otf
          weight: 900

  assets:
    - assets/images/
    - assets/avatars/
    - assets/icons/
    - assets/fonts/ghaithsans/
    - lib/localization/lang/ar.json
    - lib/localization/lang/en.json
